[build.environment]
  NPM_FLAGS = "--prefix=/dev/null"
  NODE_VERSION = "14"
  PLAYWRIGHT_BROWSERS_PATH = "0"

[build]
  publish = "dist"
  command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm run build"

[[redirects]]
  from = "/2021/bright-horizon-vue-and-vite/*"
  to = "/2021/bright-horizon-vue-and-vite/index.html"
  status = 200

[[redirects]]
  from = "/2021/leanera-design-tokens/*"
  to = "/2021/leanera-design-tokens/index.html"
  status = 200

[[redirects]]
  from = "/2021/leanera-accessible-routing-spa/*"
  to = "/2021/leanera-accessible-routing-spa/index.html"
  status = 200

[[redirects]]
  from = "/"
  to = "https://johannschopplich.com"
  status = 302
